server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: task-management-system
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    mixed: true

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    org.springframework: WARN
